CfgVars = { }

CfgVars["lottery"] = 1 --Lottery is enabled or disabled

CfgVars["lottoticketcost"] = 100 --How much each ticket costs
CfgVars["lottoautodraw"] = 9 --When this many tickets have been sold, automatically pick a number. set to 0 for NEVER auto draw
CfgVars["lottodrawtime"] = 300 --How long between each number being called (provided that the autodraw doesnt kick in). 0 for NEVER draw (except for auto)

--Fireworks
CfgVars["fireworkscost"] = 500

CfgVars["warrantcost"] = 50
CfgVars["jeepcost"] = 500
CfgVars["armorcost"] = 700
CfgVars["steroidcost"] = 1000
CfgVars["magicbulletcost"] = 1500
CfgVars["allowturrets"] = 1
CfgVars["allowsteroids"] = 1
CfgVars["allowjeeps"] = 1
CfgVars["hltvproxywashere"] = 1
CfgVars["allowhelmet"] = 1
CfgVars["qetcost"] = 100
CfgVars["turretcost"] = 1000
CfgVars["turretmax"] = 4
CfgVars["airboatcost"] = 400
CfgVars["allowairboats"] = 1
CfgVars["allowdispensers"] = 1
CfgVars["dispensercost"] = 400
CfgVars["dispensermax"] = 2
CfgVars["spawncost"] = 150
CfgVars["allowspawn"] = 1
CfgVars["allowregen"] = 1
CfgVars["regencost"] = 1000
CfgVars["allowshield"] = 1
CfgVars["shieldcost"] = 500
CfgVars["ampcost"] = 2000
CfgVars["allowamp"] = 1
CfgVars["painkillercost"] = 2000
CfgVars["allowpainkiller"] = 1
CfgVars["knifecost"] = 150
CfgVars["lockpickcost"] = 150
CfgVars["weldercost"] = 750
CfgVars["allowwelder"] = 1
CfgVars["maxprinters"] = 1
CfgVars["bigbombcost"] = 100000
CfgVars["gasgrenadecost"] = 400
CfgVars["molotovcost"] = 400
CfgVars["maxstills"] = 10
CfgVars["stillcost"] = 1000
CfgVars["metlabstable"] = 25000
CfgVars["rpgcost"] = 5000
CfgVars["galilcost"] = 3000
CfgVars["ammorocketcost"] = 50
CfgVars["ammosnipercost"] = 60
CfgVars["ammodartcost"] = 50
CfgVars["ammofuelcost"] = 70

CfgVars["bronzeprintercost"] = 1500
CfgVars["silverprintercost"] = 20000
CfgVars["goldprintercost"] = 150000
CfgVars["platinumprintercost"] = 750000
CfgVars["diamondprintercost"] = 1500000
CfgVars["nukeprintercost"] = 100000000

CfgVars["paracost"] = 5000
CfgVars["autosnipecost"] = 3500
CfgVars["augcost"] = 2000
CfgVars["autoshotguncost"] = 2500
CfgVars["uspcost"] = 220
CfgVars["mac10pistcost"] = 420
CfgVars["tmppistcost"] = 530
CfgVars["elitescost"] = 350
CfgVars["maxhitman"] = 3
CfgVars["maxspec"] = 4
CfgVars["gunvaultcost"] = 300
CfgVars["gunfactorycost"] = 1000
CfgVars["maxgunfactory"] = 2
CfgVars["maxgunvaults"] = 5
CfgVars["pillboxcost"] = 300
CfgVars["allowreflect"] = 1
CfgVars["reflectcost"] = 2000
CfgVars["drugfactorycost"] = 500
CfgVars["maxdrugfactory"] = 2
CfgVars["worldslayercost"] = 2500
CfgVars["allowfocus"] = 1
CfgVars["focuscost"] = 300
CfgVars["scannercost"] = 250
CfgVars["allowantidote"] = 1
CfgVars["antidotecost"] = 1000
CfgVars["generatorcost"] = 400
CfgVars["supergeneratorcost"] = 1400
CfgVars["shockwavecost"] = 400
CfgVars["doubletapcost"] = 600
CfgVars["knockbackcost"] = 400
CfgVars["magicbulletcost"] = 400
CfgVars["leechcost"] = 400
CfgVars["adrenalinecost"] = 700
CfgVars["doublejumpcost"] = 400
CfgVars["radartowercost"] = 400
CfgVars["armorpiercercost"] = 400
CfgVars["maxgenerator"] = 5
CfgVars["maxsupergenerator"] = 2
CfgVars["maxmethlab"] = 3
CfgVars["maxstablemethlab"] = 3
CfgVars["methlabcost"] = 1000
CfgVars["toolkitcost"] = 100
CfgVars["steroidduration"] = 140
CfgVars["regenduration"] = 100
CfgVars["ampduration"] = 100
CfgVars["painkillerduration"] = 60
CfgVars["reflectduration"] = 60
CfgVars["focusduration"] = 60
CfgVars["antidoteduration"] = 100
CfgVars["magicbulletduration"] = 60
CfgVars["leechduration"] = 100
CfgVars["doubletapduration"] = 100
CfgVars["shockwaveduration"] = 60
CfgVars["doublejumpduration"] = 250
CfgVars["knockbackduration"] = 110
CfgVars["adrenalineduration"] = 130
CfgVars["armorpiercerduration"] = 60
CfgVars["randomduration"] = 100
CfgVars["superduration"] = 100
CfgVars["uberduration"] = 200
CfgVars["scancost"]=25
CfgVars["maxsigns"]=2
CfgVars["flamethrowercost"]=2100
CfgVars["tmpcost"]=1200
CfgVars["maxbronzeprinters"]=6
CfgVars["maxsilverprinters"]=4
CfgVars["maxwashingmachines"]=1
CfgVars["maxgoldprinters"]=2
CfgVars["maxplatinumprinters"]=2
CfgVars["maxdiamondprinters"]=1
CfgVars["maxnuclearprinters"]=1
CfgVars["bigbombmax"]=4
CfgVars["maxadminprinters"]=1
CfgVars["maxdonatorprinters"]=2

CfgVars["crosshair"] = 1; --Crosshairs enabled?
CfgVars["strictsuicide"] = 0;
CfgVars["adminsents"] = 1; --Should all SENTs be admin only?
CfgVars["adminsweps"] = 1; --Should all sweps be admin only?

CfgVars[""] = 10000
CfgVars["ak47cost"] = 2000
CfgVars["mp5cost"] = 1600
CfgVars["m16cost"] = 1400
CfgVars["mac10cost"] = 1100
CfgVars["umpcost"] = 1300
CfgVars["shotguncost"] = 1500
CfgVars["snipercost"] = 2200
CfgVars["flashbangcost"] = 250
CfgVars["grenadecost"] = 300
CfgVars["deaglecost"] = 210
CfgVars["fivesevencost"] = 230
CfgVars["glockcost"] = 220
CfgVars["p228cost"] = 200
CfgVars["druglabcost"] = 1000
CfgVars["gunlabcost"] = 600
CfgVars["drugpayamount"] = 25
CfgVars["ammopistolcost"] = 20
CfgVars["ammoriflecost"] = 40
CfgVars["ammoshotguncost"] = 60
CfgVars["healthcost"] = 250
CfgVars["jailtimer"] = 40
CfgVars["whisperradius"] = 90
CfgVars["talkradius"] = 250
CfgVars["yellradius"] = 550
CfgVars["doorcost"] = 30
CfgVars["zombiescore"] = 10
CfgVars["microwavefoodcost"] = 40
CfgVars["maxdruglabs"] = 5
CfgVars["maxmicrowaves"] = 2
CfgVars["maxgunlabs"] = 2
CfgVars["allowgang"] = 1
CfgVars["maxgangsters"] = 6
CfgVars["allowmedics"] = 1
CfgVars["maxmedics"] = 6
CfgVars["allowdealers"] = 1
CfgVars["maxgundealers"] = 4
CfgVars["allowcooks"] = 1
CfgVars["allowvuvu"] = 1
CfgVars["maxcooks"] = 4
CfgVars["maxvuvu"] = 100
CfgVars["maxlamp"] = 3
CfgVars["maxow"] = 5

CfgVars["EquipmentDecayTimer"] = 3
CfgVars["WeaponDecayTimer"] = 3
CfgVars["DrugDecayTimer"] = 3
CfgVars["paydelay"] = 20

CfgVars["upgradecost"] = 1 // upgrade cost is a multiplier of the thing's price. level 2 upgrade will be double of whats set here. 0 = free
// example: turret costs 300. first upgrade costs 300 which is the turret's cost, and second upgrade costs 600, which is double that.

CfgVars["afktime"] = 600

drugeffect_doubletapmod = 0.675
drugeffect_armorpiercermod = 1.25
drugeffect_shockwavemultiplier = 1